### ISSUE TITLE
Change Default Git Branch from master to main

### ISSUE THREAD

**Issue by Macbet** [ganochenkodg/imagegate-webhook#1]
Given the recent industry-wide shift in inclusive language and the subsequent decision by the Git project and various organizations to rename the default branch from master to main, it would be beneficial for this project to follow this best practice as well. This would align our project with industry standards, enhance its inclusivity, and remove any potential for misinterpretation.

I propose that we rename the default branch in this repository from master to main.

To achieve this, the following steps will be necessary:

Notify all contributors of this upcoming change, along with a date when it will occur.
Create a new branch main from the current HEAD of master.
Change the default branch to main in the repository settings.
Update any scripts, CI/CD pipelines, or documentation that reference the master branch.
Delete the master branch after a reasonable period, and after verifying that all necessary updates have been made.

An alternative could be to choose a different name for the default branch, but main is currently the most commonly used and is the new standard suggested by GitHub.

The primary reason behind this change is inclusivity. Many communities and companies have decided to replace certain terms, including the master branch in Git, with more inclusive language. For a detailed explanation of the reasoning behind this change, please refer to [this post](https://sfconservancy.org/news/2020/jun/23/gitbranchname/) by Software Freedom Conservancy.

**Comment by ganochenkodg** [comment]
Thank you for your message regarding the proposed change to rename the default branch from "master" to "main." I have carefully considered your request, but after thorough evaluation, I have decided not to proceed with this change at this time. Allow me to explain my reasoning:

While I understand the recent industry-wide shift towards inclusive language and the decision by the Git project and other organizations to adopt the "main" branch naming convention, it is important to note that the default branch name in a Git repository is merely a label and does not inherently perpetuate any form of exclusion or discrimination. It is a technical term used within the context of version control systems.

The intention behind the change is commendable, as promoting inclusivity and aligning with industry standards are indeed important goals. However, it is essential to prioritize efforts that have a more substantial impact on inclusivity and diversity in our project and community. Changing the default branch name, while symbolic, does not directly address the core issues of inclusivity and diversity that we should be focusing on.

Furthermore, making this change would require significant effort from contributors, such as updating local repositories, modifying CI/CD pipelines, and updating documentation and scripts that reference the default branch. This process could introduce potential disruptions and complexities, especially for contributors who are accustomed to the existing workflow.

Instead of investing resources and time into this change, I believe it would be more effective to focus on promoting a welcoming and inclusive environment within our project. This can be achieved through clear and comprehensive documentation, fostering respectful and inclusive communication, and actively encouraging diverse participation and collaboration.

I appreciate your understanding and support in prioritizing efforts that have a more substantial impact on inclusivity and diversity within our project. If you have any further questions or suggestions, please don't hesitate to reach out.

Anyway thank you for your suggestion!
